### ISSUE TITLE
Investigate unexpected crash of live.geppetto.org

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#124]

**Comment by tarelli** [comment]
The server crashed tonight around 2am GMT while running an SPH simulation with the following exception:
```
[2015-01-23 01:25:23.408] ERROR Thread-717                   System.err                                                        Exception in thread "Thread-717" java.lang.OutOfMemoryError: Java heap space 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at java.util.Arrays.copyOfRange(Arrays.java:2694) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at java.lang.String.<init>(String.java:203) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at java.lang.StringBuffer.toString(StringBuffer.java:561) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at java.io.StringWriter.toString(StringWriter.java:210) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at com.google.gson.Gson.toJson(Gson.java:481) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at com.google.gson.Gson.toJson(Gson.java:460) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at org.geppetto.frontend.controllers.GeppettoServletController.messageClient(GeppettoServletController.java:680) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at org.geppetto.frontend.MultiuserSimulationCallback.updateReady(MultiuserSimulationCallback.java:114) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at org.geppetto.simulation.SimulationThread.updateRuntimeTreeClient(SimulationThread.java:120) 
[2015-01-23 01:25:23.409] ERROR Thread-717                   System.err                                                        	at org.geppetto.simulation.SimulationThread.run(SimulationThread.java:90) 
```

**Comment by tarelli** [comment]
Live is very stable now, no crashes in a long time.
