### ISSUE TITLE
Latest development version failing: org.geppetto.core.features.IFeature not found

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#389]
Trace from Virgo after running ./startup.sh:

```
...
[2015-04-16 09:58:05.849] deployer-recovery            <DE0004I> Starting bundle 'multi-artifact.plan-1-synthetic.context' version '1.0.0'. 
[2015-04-16 09:58:05.851] start-signalling-2           <DE0005I> Started bundle 'multi-artifact.plan-1-synthetic.context' version '1.0.0'. 
[2015-04-16 09:58:05.895] startup-readiness            <KE0007I> Virgo ready. Started for 23.81s. 
[2015-04-16 09:58:06.877] fs-watcher                   <HD0001I> Hot deployer processing 'INITIAL' event for file 'org.eclipse.virgo.apps.repository_3.6.2.RELEASE.par'. 
[2015-04-16 09:58:06.878] fs-watcher                   <HD0005I> Hot deploy not performed because file 'org.eclipse.virgo.apps.repository_3.6.2.RELEASE.par' is already deployed. 
[2015-04-16 09:58:06.879] fs-watcher                   <HD0001I> Hot deployer processing 'INITIAL' event for file 'org.eclipse.virgo.apps.splash_3.6.2.RELEASE.jar'. 
[2015-04-16 09:58:06.880] fs-watcher                   <HD0005I> Hot deploy not performed because file 'org.eclipse.virgo.apps.splash_3.6.2.RELEASE.jar' is already deployed. 
[2015-04-16 09:58:06.881] fs-watcher                   <HD0001I> Hot deployer processing 'INITIAL' event for file 'org.eclipse.virgo.management.console_3.6.2.RELEASE.jar'. 
[2015-04-16 09:58:06.882] fs-watcher                   <HD0005I> Hot deploy not performed because file 'org.eclipse.virgo.management.console_3.6.2.RELEASE.jar' is already deployed. 
[2015-04-16 09:58:06.883] fs-watcher                   <HD0001I> Hot deployer processing 'INITIAL' event for file 'geppetto.plan'. 
[2015-04-16 09:58:06.884] fs-watcher                   <HD0005I> Hot deploy not performed because file 'geppetto.plan' is already deployed. 
[2015-04-16 09:58:07.161] region-dm-2                  <AG0000E> Application context creation failure for bundle 'multi-artifact.plan-1-org.geppetto.solver.sph' version '0.2.2'. org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SPHSolverExporter': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SPHSolverService' defined in BeanDefinition defined in URL [bundleentry://152.fwk59912595/META-INF/spring/osgi-config.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org.geppetto.core.features.IFeature not found from bundle [multi-artifact.plan-1-org.geppetto.solver.sph]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:567)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:60)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:325)
	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:290)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137)
	at org.eclipse.virgo.kernel.agent.dm.ContextPropagatingTaskExecutor$2.run(ContextPropagatingTaskExecutor.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SPHSolverService' defined in BeanDefinition defined in URL [bundleentry://152.fwk59912595/META-INF/spring/osgi-config.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org.geppetto.core.features.IFeature not found from bundle [multi-artifact.plan-1-org.geppetto.solver.sph]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isSingleton(AbstractBeanFactory.java:408)
	at org.eclipse.gemini.blueprint.service.exporter.support.OsgiServiceFactoryBean.afterPropertiesSet(OsgiServiceFactoryBean.java:193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org.geppetto.core.features.IFeature not found from bundle [multi-artifact.plan-1-org.geppetto.solver.sph]
	at com.sun.proxy.$Proxy86.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Proxy.newInstance(Proxy.java:764)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:755)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:117)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:112)
	at org.springframework.aop.scope.ScopedProxyFactoryBean.setBeanFactory(ScopedProxyFactoryBean.java:109)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1475)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	... 26 common frames omitted

[2015-04-16 09:58:07.184] start-signalling-2           <DE0010I> Stopping plan 'multi-artifact.plan' version '1.0.0'. 
[2015-04-16 09:58:07.186] start-signalling-2           <DE0010I> Stopping bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.2.2'. 
[2015-04-16 09:58:07.218] start-signalling-2           <DE0011I> Stopped bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.2.2'. 
[2015-04-16 09:58:07.231] start-signalling-2           <DE0010I> Stopping bundle 'multi-artifact.plan-1-org.geppetto.model.sph' version '0.2.2'. 
[2015-04-16 09:58:07.247] start-signalling-4           <DE0006E> Start failed for bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.2.2'. java.lang.RuntimeException: Bundle 'multi-artifact.plan-1-org.geppetto.core_0.2.2 [149]' stopped
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$StartupTrackerBundleListener.bundleChanged(BundleStartTracker.java:250)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:847)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEventPrivileged(Framework.java:1568)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1504)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1499)
	at org.eclipse.osgi.framework.internal.core.BundleHost.stopWorker(BundleHost.java:526)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:465)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:457)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleDriver.stop(StandardBundleDriver.java:281)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.doStop(StandardBundleInstallArtifact.java:315)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.stop(StandardBundleInstallArtifact.java:301)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardPlanInstallArtifact.doStop(StandardPlanInstallArtifact.java:143)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.stop(AbstractInstallArtifact.java:360)
	at org.eclipse.virgo.kernel.install.artifact.internal.AtomicInstallArtifactLifecycleListener.onStartFailed(AtomicInstallArtifactLifecycleListener.java:73)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStartFailed(StandardArtifactStateMonitor.java:242)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartFailed(AbstractInstallArtifact.java:329)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$1(AbstractInstallArtifact.java:325)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalFailure(AbstractInstallArtifact.java:264)
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[2015-04-16 09:58:07.255] start-signalling-4           <DE0006E> Start failed for plan 'multi-artifact.plan' version '1.0.0'. java.lang.RuntimeException: Bundle 'multi-artifact.plan-1-org.geppetto.core_0.2.2 [149]' stopped
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$StartupTrackerBundleListener.bundleChanged(BundleStartTracker.java:250)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:847)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEventPrivileged(Framework.java:1568)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1504)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1499)
	at org.eclipse.osgi.framework.internal.core.BundleHost.stopWorker(BundleHost.java:526)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:465)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:457)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleDriver.stop(StandardBundleDriver.java:281)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.doStop(StandardBundleInstallArtifact.java:315)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.stop(StandardBundleInstallArtifact.java:301)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardPlanInstallArtifact.doStop(StandardPlanInstallArtifact.java:143)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.stop(AbstractInstallArtifact.java:360)
	at org.eclipse.virgo.kernel.install.artifact.internal.AtomicInstallArtifactLifecycleListener.onStartFailed(AtomicInstallArtifactLifecycleListener.java:73)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStartFailed(StandardArtifactStateMonitor.java:242)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartFailed(AbstractInstallArtifact.java:329)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$1(AbstractInstallArtifact.java:325)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalFailure(AbstractInstallArtifact.java:264)
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[2015-04-16 09:58:07.262] start-signalling-2           <DE0011I> Stopped bundle 'multi-artifact.plan-1-org.geppetto.model.sph' version '0.2.2'. 
[2015-04-16 09:58:07.273] start-signalling-2           <DE0010I> Stopping bundle 'multi-artifact.plan-1-org.geppetto.model.neuroml' version '0.2.2'. 
[2015-04-16 09:58:07.282] start-signalling-4           <DE0006E> Start failed for bundle 'multi-artifact.plan-1-org.geppetto.model.sph' version '0.2.2'. java.lang.RuntimeException: Bundle 'multi-artifact.plan-1-org.geppetto.model.sph_0.2.2 [150]' stopped
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$StartupTrackerBundleListener.bundleChanged(BundleStartTracker.java:250)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:847)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEventPrivileged(Framework.java:1568)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1504)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1499)
	at org.eclipse.osgi.framework.internal.core.BundleHost.stopWorker(BundleHost.java:526)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:465)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.stop(AbstractBundle.java:457)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleDriver.stop(StandardBundleDriver.java:281)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.doStop(StandardBundleInstallArtifact.java:315)
	at org.eclipse.virgo.kernel.install.artifact.internal.bundle.StandardBundleInstallArtifact.stop(StandardBundleInstallArtifact.java:301)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardPlanInstallArtifact.doStop(StandardPlanInstallArtifact.java:143)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.stop(AbstractInstallArtifact.java:360)
	at org.eclipse.virgo.kernel.install.artifact.internal.AtomicInstallArtifactLifecycleListener.onStartFailed(AtomicInstallArtifactLifecycleListener.java:73)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStartFailed(StandardArtifactStateMonitor.java:242)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartFailed(AbstractInstallArtifact.java:329)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$1(AbstractInstallArtifact.java:325)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalFailure(AbstractInstallArtifact.java:264)
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pgleeson** [comment]
Btw, I'm using scripts in https://github.com/openworm/org.geppetto/tree/development/utilities/source_setup to update/deploy etc.

**Comment by tarelli** [comment]
@pgleeson IFeature is there, see [here](https://github.com/openworm/org.geppetto.core/blob/development/src/main/java/org/geppetto/core/features/IFeature.java) I'm sure it's a local problem since we're also on dev. I'd advise running mvn install on all the bundles and use the update_server script afterwards making sure there are no old versions of core trickling around.

**Comment by pgleeson** [comment]
Have cleaned and rebuilt locally, but the problem persists. Think it's more of an issue related to SPH. This error line appears every minute or so when the server is running:

[2015-04-16 15:20:10.739] service-monitor-thread-1     <KE0100W> Reference '&SPHSolver' in bundle 'multi-artifact.plan-1-org.geppetto.simulator.sph' version '0.2.2' is waiting for service with filter '(&(objectClass=org.geppetto.core.solver.ISolver)(|(org.eclipse.gemini.blueprint.bean.name=SPHSolverService)(org.springframework.osgi.bean.name=SPHSolverService)(osgi.service.blueprint.compname=SPHSolverService)))'.

**Comment by tarelli** [comment]
After a number of cleaning I managed to reproduce this with solver.sph, looking at it.

**Comment by tarelli** [comment]
@pgleeson check with the latest which include this fix https://github.com/openworm/org.geppetto.solver.sph/commit/78dba6b 
The interface needs to be imported manually because there is no code that references it directly from the solver sph bundle therefore the maven bundle plugin doesn't automatically include it in the MANIFEST file that gets generated.

**Comment by pgleeson** [comment]
Great! Works for me now.

**Comment by tarelli** [comment]
@pgleeson great, thanks for catching this!
