### ISSUE TITLE
Error Loading - The C. Elegans Muscle Model

### ISSUE THREAD

**Issue by wanermiranda** [openworm/org.geppetto#465]
There is an error while opening one of live models. Here is the stack trace:
Houston, we have a problem

Error populating the model tree for net1.electrical
Details

org.geppetto.core.common.GeppettoExecutionException: org.geppetto.core.common.GeppettoExecutionException: org.geppetto.core.model.ModelInterpreterException: org.geppetto.core.model.ModelInterpreterException: java.lang.NullPointerException

**Comment by tarelli** [comment]
@wanermiranda thanks for reporting this, I'll have a look into it, might be that something in the model itself changed since when we release all samples are tested.

**Comment by wanermiranda** [comment]
Thanks @tarelli... I'll be waiting =D

**Comment by tarelli** [comment]
@wanermiranda found the cause:

https://github.com/openworm/muscle_model/commit/ea88ef090571f828f1ad9b9a212d07b3d0ee3281#diff-6b0640d9c3b5322c196b84e294d235df

The exception thrown by one of the NeuroML libraries is:

```
Caused by: java.lang.NullPointerException: null
	at org.neuroml.export.info.model.HHVariableToIHHExpressionAdapter.getType(HHVariableToIHHExpressionAdapter.java:36)
	at org.neuroml.export.info.model.ChannelMLHHExpression.<init>(ChannelMLHHExpression.java:10)
	at org.neuroml.export.info.model.HHTauInfProcessor.hhVarToExpr(HHTauInfProcessor.java:21)
	at org.neuroml.export.info.model.HHTauInfProcessor.<init>(HHTauInfProcessor.java:15)
	at org.neuroml.export.info.model.ChannelInfoExtractor.<init>(ChannelInfoExtractor.java:78)
	at org.neuroml.export.info.InfoTreeCreator.createPropertiesFromStandaloneComponent(InfoTreeCreator.java:161)
	at org.geppetto.model.neuroml.utils.modeltree.PopulateSummaryNodesModelTreeUtils.addInfoNode(PopulateSummaryNodesModelTreeUtils.java:86)
	at org.geppetto.model.neuroml.utils.modeltree.PopulateNeuroMLModelTreeUtils.addInfoNode(PopulateNeuroMLModelTreeUtils.java:175)
	at org.geppetto.model.neuroml.utils.modeltree.PopulateModelTree.populateModelTree(PopulateModelTree.java:177)
	... 19 common frames omitted
```
@pgleeson looking into it

**Comment by tarelli** [comment]
@wanermiranda the model (the older working version) was restored on live.geppetto.org with the 0.2.7 release. Now we are pointing to a snapshot which should shield us from these problems.
