### ISSUE TITLE
Installation issue with merged instance/type refactor

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#470]
@tarelli @adrianq I get the following error in Virgo after updating to the latest development branches & successful mvn installing & copying to server:

```
...
[2016-01-29 14:11:34.403] deployer-recovery            <DE0000I> Installing plan 'multi-artifact.plan' version '1.0.0'. 
[2016-01-29 14:11:34.427] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model' version '0.2.7'. 
[2016-01-29 14:11:34.564] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.2.7'. 
[2016-01-29 14:11:34.570] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model.neuroml' version '0.2.7'. 
[2016-01-29 14:11:34.574] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model.swc' version '0.2.7'. 
[2016-01-29 14:11:34.588] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.simulation' version '0.2.7'. 
[2016-01-29 14:11:34.755] deployer-recovery            <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.frontend' version '0.2.7'. 
[2016-01-29 14:11:34.756] deployer-recovery            <DE0700E> Cannot find bundle 'org.geppetto.testbackend' version range '[0.2.7, oo)' in repository 'ext-usr'. 
[2016-01-29 14:11:34.759] deployer-recovery            <DE0002E> Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Deployment of plan 'multi-artifact.plan' version '1.0.0' in scope 'null' failed: bundle 'org.geppetto.testbackend' in version range '[0.2.7, oo)' not found
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:116)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.access$0(PlanResolver.java:92)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver$1.visit(PlanResolver.java:86)
	at org.eclipse.virgo.util.common.ThreadSafeGraphNode.visitInternal(ThreadSafeGraphNode.java:193)
	at org.eclipse.virgo.util.common.ThreadSafeGraphNode.visit(ThreadSafeGraphNode.java:184)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.transform(PlanResolver.java:82)
	at org.eclipse.virgo.kernel.install.pipeline.stage.transform.internal.TransformationStage.doProcessGraph(TransformationStage.java:54)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.recoverDeployment(PipelinedApplicationDeployer.java:329)
	at org.eclipse.virgo.kernel.deployer.core.internal.recovery.RecoveryAgent$1.run(RecoveryAgent.java:71)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.virgo.nano.deployer.api.core.DeploymentException: bundle 'org.geppetto.testbackend' in version range '[0.2.7, oo)' not found
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.obtainInstallArtifactGraph(PlanResolver.java:165)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:101)
	... 16 common frames omitted

[2016-01-29 14:11:34.761] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.model' version '0.2.7'. 
[2016-01-29 14:11:34.761] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.2.7'. 
[2016-01-29 14:11:34.762] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.model.neuroml' version '0.2.7'. 
[2016-01-29 14:11:34.763] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.model.swc' version '0.2.7'. 
[2016-01-29 14:11:34.764] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.simulation' version '0.2.7'. 
[2016-01-29 14:11:34.765] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.frontend' version '0.2.7'. 
[2016-01-29 14:11:34.766] deployer-recovery            <DE0003E> Install failed for plan 'multi-artifact.plan' version '1.0.0'. 
[2016-01-29 14:11:34.767] deployer-recovery            <DE0200E> Recovery of artifact from URI 'file:/home/padraig/osb-explorer/pickup/geppetto.plan' failed. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Deployment of plan 'multi-artifact.plan' version '1.0.0' in scope 'null' failed: bundle 'org.geppetto.testbackend' in version range '[0.2.7, oo)' not found
```

Anything to do with org.geppetto.testbackend being in geppetto.plan, but not pom.xml?

**Comment by tarelli** [comment]
@pgleeson try pulling the latest from org.geppetto, the testbackend should not be deployed to virgo.

**Comment by pgleeson** [comment]
That worked fine, and now Virgo starts up without errors. However I get the constant spinning logo when I try to load a cell or network. Found this in the logs:

```
...
[2016-01-29 15:23:00.571] INFO  http-bio-8080-exec-7         org.geppetto.frontend.messaging.DefaultMessageSender              Sending message to the client took 3ms 
[2016-01-29 15:23:00.593] ERROR http-bio-8080-exec-7         org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
	at org.geppetto.simulation.manager.GeppettoManager.loadProject(GeppettoManager.java:130)
	at org.geppetto.frontend.controllers.ConnectionHandler.loadGeppettoProject(ConnectionHandler.java:179)
	at org.geppetto.frontend.controllers.ConnectionHandler.loadProjectFromURL(ConnectionHandler.java:163)
	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:200)
	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[2016-01-29 15:23:14.643] INFO  System Bundle Shutdown       o.e.g.b.extender.internal.activator.ContextLoaderListener         Stopping [org.eclipse.gemini.blueprint.extender] bundle v.[1.0.2.RELEASE] 
[2016-01-29 15:23:14.651] INFO  kernel-dm-8                  o.e.g.blueprint.context.support.OsgiBundleXmlApplicationContext   Unpublishing application context OSGi service for bundle Virgo Kernel Runtime Artifact Model (org.eclipse.virgo.kernel.model) 
[2016-01-29 15:23:14.651] INFO  kernel-dm-8                  o.e.g.blueprint.context.support.OsgiBundleXmlApplicationContext   Closing OsgiBundleXmlApplicationContext(bundle=org.eclipse.virgo.kernel.model, config=osgibundle:/META-INF/spring/*.xml): startup date [Fri Jan 2
9 15:21:34 GMT 2016]; root of context hierarchy 
```

Do I need to do anything like clean/refresh my local database of projects for the refactored code?

**Comment by tarelli** [comment]
@pgleeson undeploy the persistence bundle (uncommenting it from the geppetto.plan) and try the samples. The DB will have to be recreated with the new schema (user permissions + some other changes).

**Comment by tarelli** [comment]
@pgleeson btw this is to clean your local DB 

```
drop database geppetto;
create database geppetto;
drop user user_name;
flush privileges;
create user user_name identified by 'password';
grant all privileges on geppetto.* to 'user_name'@'localhost' identified by 'password';
```

**Comment by pgleeson** [comment]
Installs fine now and included examples work when persistence bundle is not included. Eagerly awaiting testing it integrated with osb/redmine...
