### ISSUE TITLE
Error in OSB points to bug while closing a project.

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto#509]
`[2016-06-17 17:35:40.727] ERROR http-bio-8080-exec-270       org.geppetto.frontend.controllers.ConnectionHandler               Error while closing the project org.geppetto.core.common.GeppettoExecutionException: A project without a runtime project cannot be closed
    at org.geppetto.simulation.manager.GeppettoManager.closeProject(GeppettoManager.java:156)
    at org.geppetto.frontend.controllers.ConnectionHandler.closeProject(ConnectionHandler.java:1072)
    at org.geppetto.frontend.controllers.WebsocketConnection.onClose(WebsocketConnection.java:131)
    at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:226)
    at org.apache.catalina.websocket.WsOutbound.flush(WsOutbound.java:254)
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:218)
    at org.geppetto.frontend.controllers.ConnectionsManager.purgeLostConnections(ConnectionsManager.java:69)
    at org.geppetto.frontend.controllers.ConnectionsManager.addConnection(ConnectionsManager.java:52)
    at org.geppetto.frontend.controllers.WebsocketConnection.onOpen(WebsocketConnection.java:123)
    at org.apache.catalina.websocket.StreamInbound.onUpgradeComplete(StreamInbound.java:251)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:642)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[2016-06-17 17:35:40.728] ERROR http-bio-8080-exec-270       org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
    at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
    at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1175)
    at org.geppetto.frontend.controllers.ConnectionsManager.removeConnection(ConnectionsManager.java:89)
    at org.geppetto.frontend.controllers.ConnectionHandler.closeProject(ConnectionHandler.java:1079)
    at org.geppetto.frontend.controllers.WebsocketConnection.onClose(WebsocketConnection.java:131)
    at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:226)
    at org.apache.catalina.websocket.WsOutbound.flush(WsOutbound.java:254)
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:218)
    at org.geppetto.frontend.controllers.ConnectionsManager.purgeLostConnections(ConnectionsManager.java:69)
    at org.geppetto.frontend.controllers.ConnectionsManager.addConnection(ConnectionsManager.java:52)
    at org.geppetto.frontend.controllers.WebsocketConnection.onOpen(WebsocketConnection.java:123)
    at org.apache.catalina.websocket.StreamInbound.onUpgradeComplete(StreamInbound.java:251)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:642)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by slarson** [comment]
Seems like we could expand [this test case](https://github.com/openworm/org.geppetto.simulation/blob/master/src/test/java/org/geppetto/simulation/test/GeppettoManagerTest.java#L728) to try to simulate this bug.  I think @jrmartin had a theory about the case in which this problem could happen that he could try to implement here.

**Comment by jrmartin** [comment]
Another error encountered while creating and deleting new experiments. (Also cloning)

[2016-07-08 08:14:21.300] WARN  http-bio-8080-exec-3         org.geppetto.persistence.db.DBManager                             Could not delete data javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:546)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:171)
	at org.geppetto.persistence.db.DBManager.deleteEntity(DBManager.java:197)
	at org.geppetto.persistence.GeppettoDataManager.deleteExperiment(GeppettoDataManager.java:332)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy111.deleteExperiment(Unknown Source)
	at org.geppetto.simulation.manager.GeppettoManager.deleteExperiment(GeppettoManager.java:425)
	at org.geppetto.frontend.controllers.ConnectionHandler.deleteExperiment(ConnectionHandler.java:797)
	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:298)
	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`geppetto`.`geppettoproject_experiments`, CONSTRAINT `GEPPETTOPROJECT_EXPERIMENTS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `experiment` (`ID`))
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1666)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1082)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeBatch(ParamLoggingPreparedStatement.java:366)
	at org.datanucleus.store.rdbms.SQLController.processConnectionStatement(SQLController.java:676)
	at org.datanucleus.store.rdbms.SQLController.processStatementsForConnection(SQLController.java:644)
	at org.datanucleus.store.rdbms.SQLController$1.transactionFlushed(SQLController.java:731)
	at org.datanucleus.store.connection.AbstractManagedConnection.transactionFlushed(AbstractManagedConnection.java:89)
	at org.datanucleus.store.connection.ConnectionManagerImpl$2.transactionFlushed(ConnectionManagerImpl.java:450)
	at org.datanucleus.TransactionImpl.flush(TransactionImpl.java:212)
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:276)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:107)
	... 26 common frames omitted

[2016-07-08 08:14:26.230] WARN  http-bio-8080-exec-3         org.geppetto.persistence.db.DBManager                             Could not delete data javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:546)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:171)
	at org.geppetto.persistence.db.DBManager.deleteEntity(DBManager.java:197)
	at org.geppetto.persistence.GeppettoDataManager.deleteExperiment(GeppettoDataManager.java:332)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy111.deleteExperiment(Unknown Source)
	at org.geppetto.simulation.manager.GeppettoManager.deleteExperiment(GeppettoManager.java:425)
	at org.geppetto.frontend.controllers.ConnectionHandler.deleteExperiment(ConnectionHandler.java:797)
	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:298)
	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`geppetto`.`geppettoproject_experiments`, CONSTRAINT `GEPPETTOPROJECT_EXPERIMENTS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `experiment` (`ID`))
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1666)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1082)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeBatch(ParamLoggingPreparedStatement.java:366)
	at org.datanucleus.store.rdbms.SQLController.processConnectionStatement(SQLController.java:676)
	at org.datanucleus.store.rdbms.SQLController.processStatementsForConnection(SQLController.java:644)
	at org.datanucleus.store.rdbms.SQLController$1.transactionFlushed(SQLController.java:731)
	at org.datanucleus.store.connection.AbstractManagedConnection.transactionFlushed(AbstractManagedConnection.java:89)
	at org.datanucleus.store.connection.ConnectionManagerImpl$2.transactionFlushed(ConnectionManagerImpl.java:450)
	at org.datanucleus.TransactionImpl.flush(TransactionImpl.java:212)
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:276)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:107)
	... 26 common frames omitted

**Comment by jrmartin** [comment]
`[2016-07-08 09:40:00.676] ERROR http-bio-8080-exec-2         org.geppetto.frontend.controllers.ConnectionsManager              Unable to communicate with client Socket closed. Removing connection. 
[2016-07-08 09:40:00.678] ERROR http-bio-8080-exec-2         org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1175)
	at org.geppetto.frontend.controllers.ConnectionsManager.removeConnection(ConnectionsManager.java:96)
	at org.geppetto.frontend.controllers.ConnectionsManager.purgeLostConnections(ConnectionsManager.java:82)
	at org.geppetto.frontend.controllers.ConnectionsManager.addConnection(ConnectionsManager.java:54)
	at org.geppetto.frontend.controllers.WebsocketConnection.onOpen(WebsocketConnection.java:122)
	at org.apache.catalina.websocket.StreamInbound.onUpgradeComplete(StreamInbound.java:240)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by slarson** [comment]
Should be closed in https://github.com/openworm/org.geppetto.persistence/tree/experiments_table_refactoring -- new tests in https://github.com/openworm/org.geppetto.persistence/blob/experiments_table_refactoring/src/test/java/org/geppetto/persistence/db/DBManagerTest.java appear to cover this.
