### ISSUE TITLE
Move to Virgo 3.7.2 / Spring 4

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#543]
We are currently using Virgo 3.6.x which uses Spring 3.1.1.
This is complicating things when using recent libraries since Spring 3.1.1 by now is using some old version for common libraries (see fasterxml for instance). Upgrading to Virgo 3.7 (where now the default Spring is 4.2.4) will take care of this.

**Comment by tarelli** [comment]
Created the branch virgo37spring42 for model/core/neuroml/simulation/frontend. Not yet working, see https://www.eclipse.org/forums/index.php/t/1079844/

**Comment by pgleeson** [comment]
As mentioned @tarelli I'm getting a fasterxml related error, see partial log below. Is the only solution for this to update to virgo 3.7 locally?

```
[2017-01-13 15:36:05.271] start-signalling-1           <WE0001I> Started web bundle 'org.eclipse.virgo.apps.splash' version '3.6.4.RELEASE' with context path '/'. 
[2017-01-13 15:36:05.272] start-signalling-1           <DE0005I> Started bundle 'org.eclipse.virgo.apps.splash' version '3.6.4.RELEASE'. 
[2017-01-13 15:36:05.422] start-signalling-3           <WE0001I> Started web bundle 'org.eclipse.virgo.management.console' version '3.6.4.RELEASE' with context path '/admin'. 
[2017-01-13 15:36:05.423] start-signalling-3           <DE0005I> Started bundle 'org.eclipse.virgo.management.console' version '3.6.4.RELEASE'. 
[2017-01-13 15:36:05.698] start-signalling-2           <WE0001I> Started web bundle 'org.eclipse.virgo.apps.repository-3.6.4.RELEASE-org.eclipse.virgo.apps.repository.web' version '3.6.4.RELEASE' with context path '/org.eclipse.virgo.apps.repository'. 
[2017-01-13 15:36:05.698] start-signalling-2           <DE0005I> Started bundle 'org.eclipse.virgo.apps.repository-3.6.4.RELEASE-org.eclipse.virgo.apps.repository.web' version '3.6.4.RELEASE'. 
[2017-01-13 15:36:05.699] start-signalling-2           <DE0005I> Started par 'org.eclipse.virgo.apps.repository' version '3.6.4.RELEASE'. 
[2017-01-13 15:36:16.073] deployer-recovery            <ME0003I> Dump 'serviceability/dump/2017-01-13-15-36-875' generated 
[2017-01-13 15:36:16.731] deployer-recovery            <DE0002E> Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'multi-artifact.plan-1-org.geppetto.frontend' at version '0.3.3': Cannot resolve: multi-artifact.plan-1-org.geppetto.frontend
    Resolver report:
        Uses violation: <Import-Package: org.springframework.http.converter.json; version="0.0.0"> in bundle <multi-artifact.plan-1-org.geppetto.frontend_0.3.3[1484321762789]>
            Found conflicts:
                package        'com.fasterxml.jackson.databind_2.5.3' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.5.3[84]' used by 'org.springframework.http.converter.json_3.1.3.RELEASE' in bundle 'org.springframework.web_3.1.3.RELEASE[118]'
                conflicts with 'com.fasterxml.jackson.databind_2.8.5' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.8.5[1484321762821]' used by 'org.geppetto.simulation.manager_0.3.3' in bundle 'multi-artifact.plan-1-org.geppetto.simulation_0.3.3[1484321762788]'

        Uses violation: <Import-Package: org.springframework.web.servlet.view.json; version="0.0.0"> in bundle <multi-artifact.plan-1-org.geppetto.frontend_0.3.3[1484321762789]>
            Found conflicts:
                package        'com.fasterxml.jackson.databind_2.5.3' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.5.3[84]' used by 'org.springframework.web.servlet.view.json_3.1.3.RELEASE' in bundle 'org.springframework.web.servlet_3.1.3.RELEASE[153]'
                conflicts with 'com.fasterxml.jackson.databind_2.8.5' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.8.5[1484321762821]' used by 'org.geppetto.simulation.manager_0.3.3' in bundle 'multi-artifact.plan-1-org.geppetto.simulation_0.3.3[1484321762788]'

        The bundle could not be resolved because another singleton bundle was selected. Resolver error data <org.eclipse.emf.ecore_2.11.1.v20150805-0538>. In bundle <org.eclipse.emf.ecore_2.11.0.v20150123-0347>
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.frontend; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-synthetic.context_1.0.0>
             constraint: <Import-Package: org.geppetto.frontend; version="0.0.0"> constrained to bundle <multi-artifact.plan-1-org.geppetto.frontend> constrained bundle version range "[0.3.3,0.3.3]"
            with attributes {module_scope=multi-artifact.plan-1}

        The bundle could not be resolved because another singleton bundle was selected. Resolver error data <org.eclipse.emf.common_2.11.0.v20150805-0538>. In bundle <org.eclipse.emf.common_2.11.0.v20150123-0347>

	at org.eclipse.virgo.kernel.install.pipeline.stage.resolve.internal.QuasiResolveStage.process(QuasiResolveStage.java:46)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.recoverDeployment(PipelinedApplicationDeployer.java:329)
	at org.eclipse.virgo.kernel.deployer.core.internal.recovery.RecoveryAgent$1.run(RecoveryAgent.java:71)
	at java.lang.Thread.run(Thread.java:745)

[2017-01-13 15:36:16.732] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.model' version '0.3.3'. 
[2017-01-13 15:36:16.733] deployer-recovery            <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.3.3'. 

```

**Comment by tarelli** [comment]
@pgleeson no, no need to update Virgo (and in a branch I managed to solve the problem altogether). To solve it in yours (development) for now (until I merge) you just have to remove from repository/usr of virgo the version 2.5.3 both JARs are present and they conflicting. In the branch where I fixed it we are using a les newer version of AWS which doesnt require to update fasterXML. Let me know if it works!

**Comment by pgleeson** [comment]
@tarelli I had been managing to run Geppetto after updating the development branches, usually by starting with 

     ./startup.sh -clean

It had been failing like this occasionally, but ran every ~2nd time. Now it always stalls as follows:
```
...
[2017-02-08 15:43:31.564] fs-watcher                   <DE0000I> Installing plan 'multi-artifact.plan' version '1.0.0'. 
[2017-02-08 15:43:31.599] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model' version '0.3.4'. 
[2017-02-08 15:43:31.992] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.core' version '0.3.4'. 
[2017-02-08 15:43:31.998] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model.neuroml' version '0.3.4'. 
[2017-02-08 15:43:32.000] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.model.swc' version '0.3.4'. 
[2017-02-08 15:43:32.013] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.simulation' version '0.3.4'. 
[2017-02-08 15:43:32.915] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.frontend' version '0.3.4'. 
[2017-02-08 15:43:33.354] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.persistence' version '0.3.4'. 
[2017-02-08 15:43:33.360] fs-watcher                   <DE0000I> Installing bundle 'multi-artifact.plan-1-org.geppetto.simulator.external' version '0.3.4'. 
[2017-02-08 15:44:10.552] fs-watcher                   <ME0003I> Dump 'serviceability/dump/2017-02-08-15-44-268' generated 
[2017-02-08 15:44:12.873] fs-watcher                   <DE0002E> Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'multi-artifact.plan-1-org.geppetto.core' at version '0.3.4': Cannot resolve: multi-artifact.plan-1-org.geppetto.core
    Resolver report:
        Uses violation: <Import-Package: com.amazonaws.auth; version="[1.10.0,2.0.0)"> in bundle <multi-artifact.plan-1-org.geppetto.core_0.3.4[1486568611563]>
            Found conflicts:
                package        'com.amazonaws.auth.profile_1.11.49' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.11.49.1[1486568611619]' used by 'com.amazonaws.auth_1.11.49' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.11.49.1[1486568611619]'
                conflicts with 'com.amazonaws.auth.profile_1.10.2' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.10.2.1[1486568611618]' used by 'com.amazonaws.services.s3_1.10.2' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.10.2.1[1486568611618]'
                package        'com.fasterxml.jackson.databind_2.8.5' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.8.5[1486568611800]' used by 'com.amazonaws.auth_1.11.49' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.11.49.1[1486568611619]'
                conflicts with 'com.fasterxml.jackson.databind_2.5.3' in bundle 'com.fasterxml.jackson.core.jackson-databind_2.5.3[84]' used by 'org.emfjson.jackson.databind.ser.references_0.14.0' in bundle 'org.emfjson.jackson_0.14.0[1486568611614]'

        Uses violation: <Import-Package: com.amazonaws.services.s3; version="[1.10.0,2.0.0)"> in bundle <multi-artifact.plan-1-org.geppetto.core_0.3.4[1486568611563]>
            Found conflicts:
                package        'com.amazonaws.retry.internal_1.10.2' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.10.2.1[1486568611618]' used by 'com.amazonaws.services.s3_1.10.2' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.10.2.1[1486568611618]'
                conflicts with 'com.amazonaws.retry.internal_1.11.49' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.11.49.1[1486568611619]' used by 'com.amazonaws.auth_1.11.49' in bundle 'org.apache.servicemix.bundles.aws-java-sdk_1.11.49.1[1486568611619]'

        Uses violation: <Import-Package: com.amazonaws.services.s3.model; version="[1.10.0,2.0.0)"> in bundle <multi-artifact.plan-1-org.geppetto.core_0.3.4[1486568611563]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.sun.source.tree; version="0.0.0"> in bundle <com.sun.xml.bind.jaxb-osgi_2.2.11[1486568611756]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.sun.source.util; version="0.0.0"> in bundle <com.sun.xml.bind.jaxb-osgi_2.2.11[1486568611756]>
             Resolver reported uses conflict for import
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.springframework.web.servlet; version="[3.1.3,3.1.4)">. Caused by missing constraint in bundle <org.springframework.web.portlet_3.1.3.RELEASE>
             constraint: <Import-Package: org.springframework.web.servlet; version="[3.1.3,3.1.4)">
        Uses violation: <Import-Package: org.springframework.http.converter.json; version="[3.1.3,3.1.4)"> in bundle <org.springframework.web.servlet_3.1.3.RELEASE[1486568611788]>
             Resolver reported uses conflict for import
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.jvnet.jaxb2_commons.lang; version="[0.6.0,1.0.0)">. Caused by missing constraint in bundle <org.neuroml.model_1.5.0>
             constraint: <Import-Package: org.jvnet.jaxb2_commons.lang; version="[0.6.0,1.0.0)">
        Uses violation: <Import-Package: com.sun.xml.bind.v2.model.core; version="0.0.0"> in bundle <org.jvnet.jaxb2_commons.jaxb2-basics-runtime_0.9.0[1486568611811]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.base; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[1486568611821]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.collect; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[1486568611821]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.net; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[1486568611821]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.primitives; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[1486568611821]>
             Resolver reported uses conflict for import
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.glassfish.jersey; version="[2.0.0,3.0.0)">. Caused by missing constraint in bundle <org.glassfish.jersey.core.jersey-client_2.0.0>
             constraint: <Import-Package: org.glassfish.jersey; version="[2.0.0,3.0.0)">
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.model.neuroml.features; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-synthetic.context_1.0.0>
             constraint: <Import-Package: org.geppetto.model.neuroml.features; version="0.0.0"> constrained to bundle <multi-artifact.plan-1-org.geppetto.model.neuroml> constrained bundle version range "[0.3.4,0.3.4]"
            with attributes {module_scope=multi-artifact.plan-1}

        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.core.data.model; version="[0.3.0,1.0.0)">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.persistence_0.3.4>
             constraint: <Import-Package: org.geppetto.core.data.model; version="[0.3.0,1.0.0)">
            with attributes {module_scope=multi-artifact.plan-1}

        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.core.simulator; version="[0.3.0,1.0.0)">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.simulator.external_0.3.4>
             constraint: <Import-Package: org.geppetto.core.simulator; version="[0.3.0,1.0.0)">
            with attributes {module_scope=multi-artifact.plan-1}

        The bundle could not be resolved because another singleton bundle was selected. Resolver error data <org.eclipse.emf.common_2.11.0.v20150805-0538>. In bundle <org.eclipse.emf.common_2.11.0.v20150123-0347>
        The bundle could not be resolved because another singleton bundle was selected. Resolver error data <org.eclipse.emf.ecore_2.11.1.v20150805-0538>. In bundle <org.eclipse.emf.ecore_2.11.0.v20150123-0347>
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.core.simulator; version="[0.3.0,1.0.0)">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.simulation_0.3.4>
             constraint: <Import-Package: org.geppetto.core.simulator; version="[0.3.0,1.0.0)">
            with attributes {module_scope=multi-artifact.plan-1}

        Uses violation: <Import-Package: org.springframework.http.converter.json; version="0.0.0"> in bundle <multi-artifact.plan-1-org.geppetto.frontend_0.3.4[1486568611567]>
             Resolver reported uses conflict for import constrained to bundle <org.springframework.web> constrained bundle version range "[3.1.3.RELEASE,3.1.3.RELEASE]"
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.lemsml.expr_parser.utils; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.model.neuroml_0.3.4>
             constraint: <Import-Package: org.lemsml.expr_parser.utils; version="0.0.0">
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.core.services.registry; version="[0.3.0,1.0.0)">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.model.swc_0.3.4>
             constraint: <Import-Package: org.geppetto.core.services.registry; version="[0.3.0,1.0.0)">
            with attributes {module_scope=multi-artifact.plan-1}

        An Import-Package could not be resolved. Resolver error data <Import-Package: org.glassfish.jersey.client.filter; version="[2.0.0,3.0.0)">. Caused by missing constraint in bundle <org.ngbw.java_direct_client_0.0.1>
             constraint: <Import-Package: org.glassfish.jersey.client.filter; version="[2.0.0,3.0.0)">
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.neuroml.model; version="[1.5.0,2.0.0)">. Caused by missing constraint in bundle <org.neuroml.export_1.5.0>
             constraint: <Import-Package: org.neuroml.model; version="[1.5.0,2.0.0)">

	at org.eclipse.virgo.kernel.install.pipeline.stage.resolve.internal.QuasiResolveStage.process(QuasiResolveStage.java:46)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doInstall(PipelinedApplicationDeployer.java:185)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.install(PipelinedApplicationDeployer.java:140)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.deploy(PipelinedApplicationDeployer.java:253)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deploy(HotDeployerFileSystemListener.java:225)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deployIfNotDeployed(HotDeployerFileSystemListener.java:237)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.onChange(HotDeployerFileSystemListener.java:88)
	at org.eclipse.virgo.util.io.FileSystemChecker.notifyListeners(FileSystemChecker.java:380)
	at org.eclipse.virgo.util.io.FileSystemChecker.check(FileSystemChecker.java:289)
	at org.eclipse.virgo.nano.deployer.hot.WatchTask.run(WatchTask.java:49)
	at java.lang.Thread.run(Thread.java:745)

[2017-02-08 15:44:12.875] fs-watcher                   <DE0003E> Install failed for bundle 'multi-artifact.plan-1-org.geppetto.model' version '0.3.4'. 
...

```

There are no fasterxml jars in repository/usr...
This is the same after a fresh install of Virgo 3.6.4

**Comment by tarelli** [comment]
@pgleeson make sure that the only AWS JARs in repository/usr are the ones with version 1.10.2 (should be 49 of them), Make sure org.apache.servicemix.bundles.aws-java-sdk-1.8.3_2.jar is not there and none of the *-1.11.49.jar are there (we were using these in previous versions).

![screen shot 2017-02-08 at 16 11 56](https://cloud.githubusercontent.com/assets/81127/22745710/6b553cfe-ee19-11e6-94e8-da8e541a0152.png)

**Comment by pgleeson** [comment]
@tarelli, yes, that seems to have solved that issue, thanks.

On a related note, trying to integrate some of the Lems2 libraries (e.g. https://github.com/pgleeson/expr-parser). At the moment getting errors which probably stem from the fact that they're not OSGi bundles:
```
[2017-02-08 17:11:41.085] fs-watcher                   <DE0002E> Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'multi-artifact.plan-1-org.geppetto.model.neuroml' at version '0.3.4': Cannot resolve: multi-artifact.plan-1-org.geppetto.model.neuroml
    Resolver report:
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.lemsml.exprparser.utils; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.model.neuroml_0.3.4>
             constraint: <Import-Package: org.lemsml.exprparser.utils; version="0.0.0">
        The bundle could not be resolved because another singleton bundle was selected. Resolver error data <org.eclipse.emf.common_2.11.0.v20150805-0538>. In bundle <org.eclipse.emf.common_2.11.0.v20150123-0347>
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.model.neuroml.features; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-synthetic.context_1.0.0>
             constraint: <Import-Package: org.geppetto.model.neuroml.features; version="0.0.0"> constrained to bundle <multi-artifact.plan-1-org.geppetto.model.neuroml> constrained bundle version range "[0.3.4,0.3.4]"
            with attributes {module_scope=multi-artifact.plan-1}
```
What is your preferred way to convert/configure a Maven project into OSGi (ideally not through Eclipse...)

**Comment by tarelli** [comment]
@pgleeson you can do from command line using [that jar](https://github.com/openworm/org.geppetto/tree/master/utilities/bnd). The instructions are in the readme. bnd.jar will create a new osgfied JAR.

**Comment by pgleeson** [comment]
Thanks @tarelli. Some slightly different issues from the original error exist now, opening a separate issue.

**Comment by tarelli** [comment]
@pgleeson 👍 Will keep this issue open as in the future we still want to migrate to Virgo 3.7/Spring 4 once they release it.

**Comment by pgleeson** [comment]
Sorry, forgot it was originally your issue...

**Comment by LordKrabo** [comment]
Sorry to revive this dead thread, but I'm having some similar problems to @pgleeson in running geppetto 0.3.6 using virgo 3.6.3. I've tried updating each of the repos (and using the .bnd jar to unwrap jars like @tarelli  suggested but I've hit this snag. I've also tried removing org.geppetto.model.neuroml from geppetto.plan but without luck. This is the error I hit. 

         [2017-07-04 15:35:23.013] fs-watcher                   <DE0700E> Cannot find bundle 'org.geppetto.model.neuroml' version range '[0.3.6, oo)' in repository 'stage-ext-usr'. 
        [2017-07-04 15:35:23.021] fs-watcher                   <DE0002E> Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.nano.deployer.api.core.DeploymentException:            

        Deployment of plan 'multi-artifact.plan' version '1.0.0' in scope 'null' failed: bundle 'org.geppetto.model.neuroml' in version range '[0.3.6, oo)' not found
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:116)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.access$0(PlanResolver.java:92)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver$1.visit(PlanResolver.java:86)
	 at   org.eclipse.virgo.util.common.ThreadSafeGraphNode.visitInternal(ThreadSafeGraphNode.java:193)
	 at org.eclipse.virgo.util.common.ThreadSafeGraphNode.visit(ThreadSafeGraphNode.java:184)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.transform(PlanResolver.java:82)
	 at org.eclipse.virgo.kernel.install.pipeline.stage.transform.internal.TransformationStage.doProcessGraph(TransformationStage.java:54)
	 at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	 at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	 at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	 at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	 at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	 at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doInstall(PipelinedApplicationDeployer.java:185)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.install(PipelinedApplicationDeployer.java:140)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.deploy(PipelinedApplicationDeployer.java:253)
	 at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deploy(HotDeployerFileSystemListener.java:225)
	 at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deployIfNotDeployed(HotDeployerFileSystemListener.java:237)
	 at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.onChange(HotDeployerFileSystemListener.java:88)
	 at org.eclipse.virgo.util.io.FileSystemChecker.notifyListeners(FileSystemChecker.java:380)
	 at org.eclipse.virgo.util.io.FileSystemChecker.check(FileSystemChecker.java:289)
	 at org.eclipse.virgo.nano.deployer.hot.WatchTask.run(WatchTask.java:49)
	 at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.virgo.nano.deployer.api.core.DeploymentException: bundle 'org.geppetto.model.neuroml' in version range '[0.3.6, oo)' not found
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.obtainInstallArtifactGraph(PlanResolver.java:165)
	 at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:101)
	... 23 common frames omitted

Sorry for flailing around with this :P

**Comment by LordKrabo** [comment]
I've also removed all of the .sph modules in eclipse and I will try regenerating the jars.

**Comment by LordKrabo** [comment]
Just another note, I've tried this edit to configuration/org.eclipse.virgo.repository.properties following this guide without luck (https://www.eclipse.org/forums/index.php/t/448565/)

**Comment by pgleeson** [comment]
Not sure if it will help @LordKrabo but what I find useful when updating Geppetto/switching between branches is to:
- do an mvn clean at the root of org.geppetto before rebuilding all
- remove all the *.jar files in repository/usr/ of virgo
- start virgo with ./startup.sh -clean

These often make errors on Geppetto startup magically disappear...

**Comment by LordKrabo** [comment]
Thanks @pgleeson I eventually figured it out. Perhaps @tarelli I can include this in the build docs?

**Comment by tarelli** [comment]
Needs to happen still.

**Comment by tarelli** [comment]
Still happening stale bot

**Comment by tarelli** [comment]
This is now done and merged to development!
