### ISSUE TITLE
Integrate org.model.lems libraries with Geppetto

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#552]
I'm trying to integrate the "Lems2" repos into Geppetto, see https://github.com/NeuroML/NeuroML2/issues/100 for current status (latest working versions under https://github.com/pgleeson). These are compatible, building and I've OSGi-ified them and added them on my branch of the Gepp. mvn repo here: https://github.com/openworm/org.geppetto.maven/tree/mvn-revo-pg/org

I have 2 branches of org.geppetto.model.neuroml which use these, both of which build (pulling from mvn-revo-pg), only one of which works with Geppetto:

- https://github.com/openworm/org.geppetto.model.neuroml/tree/pg_expr
This only uses https://github.com/pgleeson/expr-parser and works fine when Geppetto is run in Virgo.

- https://github.com/openworm/org.geppetto.model.neuroml/tree/pg_html_update
This uses all up to https://github.com/pgleeson/neuroml2model, builds fine, but fails with error:

```
 Resolver report:
        Uses violation: <Import-Package: org.neuroml2.model; version="0.0.0"> in bundle <multi-artifact.plan-1-org.geppetto.model.neuroml_0.3.4[1487252684517]>
            Found conflicts:
                package        'javax.xml.bind.annotation_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind.annotation_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'javax.xml.bind_2.2.11' in bundle 'jaxb-api_2.2.11[161]'
                package        'javax.xml.bind.annotation_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind.annotation_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'org.neuroml.model.util_1.5.0' in bundle 'org.neuroml.model_1.5.0[193]'
                package        'javax.xml.bind.annotation_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind.annotation_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'org.neuroml.model.util_1.5.0' in bundle 'org.neuroml.model_1.5.0[193]'
                package        'javax.xml.bind_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'org.neuroml.model.util_1.5.0' in bundle 'org.neuroml.model_1.5.0[193]'
                package        'javax.xml.bind_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'org.neuroml.model.util_1.5.0' in bundle 'org.neuroml.model_1.5.0[193]'
                package        'javax.xml.bind_2.0.0' in bundle 'org.eclipse.osgi_3.8.2.v20130124-134944[0]' used by 'org.neuroml2.model_0.0.0' in bundle 'org.neuroml.neuroml2-model-0.0.4_0.0.0[194]'
                conflicts with 'javax.xml.bind_2.2.11' in bundle 'jaxb-api_2.2.11[161]' used by 'org.neuroml.model.util_1.5.0' in bundle 'org.neuroml.model_1.5.0[193]'

        An Import-Package could not be resolved. Resolver error data <Import-Package: org.ngbw.directclient; version="[0.0.0,1.0.0)">. Caused by missing constraint in bundle <multi-artifact.plan-1-org.geppetto.simulator.external_0.3.4>
             constraint: <Import-Package: org.ngbw.directclient; version="[0.0.0,1.0.0)">
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.geppetto.simulator.remote.services; version="0.0.0">. Caused by missing constraint in bundle <multi-artifact.plan-1-synthetic.context_1.0.0>
             constraint: <Import-Package: org.geppetto.simulator.remote.services; version="0.0.0"> constrained to bundle <multi-artifact.plan-1-org.geppetto.simulator.external> constrained bundle version range "[0.3.4,0.3.4]"
            with attributes {module_scope=multi-artifact.plan-1}

        An Import-Package could not be resolved. Resolver error data <Import-Package: org.glassfish.jersey.process.internal; version="[2.0.0,3.0.0)">. Caused by missing constraint in bundle <org.glassfish.jersey.core.jersey-client_2.0.0>
             constraint: <Import-Package: org.glassfish.jersey.process.internal; version="[2.0.0,3.0.0)">
        Uses violation: <Import-Package: com.google.common.net; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[187]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.collect; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[187]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.base; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[187]>
             Resolver reported uses conflict for import
        Uses violation: <Import-Package: com.google.common.primitives; version="[14.0.0,15.0.0)"> in bundle <org.glassfish.jersey.core.jersey-common_2.0.0[187]>
             Resolver reported uses conflict for import
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.glassfish.jersey.client.filter; version="[2.0.0,3.0.0)">. Caused by missing constraint in bundle <org.ngbw.java_direct_client_0.0.1>
             constraint: <Import-Package: org.glassfish.jersey.client.filter; version="[2.0.0,3.0.0)">

	at org.eclipse.virgo.kernel.install.pipeline.stage.resolve.internal.QuasiResolveStage.process(QuasiResolveStage.java:46)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	... 10 common frames omitted
```

**Comment by tarelli** [comment]
The libraries are now working
