### ISSUE TITLE
NeuroML Model bundle 1.0.1 fails

### ISSUE THREAD

**Issue by clausagerskov** [openworm/org.geppetto#638]
NeuroML Model bundle 1.0.1 build fails:

[INFO] ---------------------< org.geppetto:model.neuroml >---------------------
[INFO] Building Geppetto NeuroML Model bundle 1.0.1                      [1/13]
[INFO] -------------------------------[ bundle ]-------------------------------
[WARNING] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-osgi:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading from org.geppetto-mvn-repo: https://raw.github.com/openworm/org.geppetto.maven/mvn-repo/org/geppetto/core/maven-metadata.xml
Downloaded from org.geppetto-mvn-repo: https://raw.github.com/openworm/org.geppetto.maven/mvn-repo/org/geppetto/core/maven-metadata.xml (296 B at 302 B/s)
Downloading from org.geppetto-mvn-repo: https://raw.github.com/openworm/org.geppetto.maven/mvn-repo/com/dropbox/core/dropbox-core-sdk/3.0.6-SNAPSHOT/maven-metadata.xml  
  
is the initial warning that could be what leads to this build error:  
  
-------------------------------------------------------------------------------
Test set: org.geppetto.model.neuroml.test.LEMSConversionServiceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.668 sec <<< FAILURE! - in org.geppetto.model.neuroml.test.LEMSConversionServiceTest
testNeuron(org.geppetto.model.neuroml.test.LEMSConversionServiceTest)  Time elapsed: 0.365 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.getMethod(Injector.java:184)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.access$000(Injector.java:69)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:168)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:165)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:164)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:235)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:175)
	at com.sun.xml.bind.v2.runtime.property.AttributeProperty.<init>(AttributeProperty.java:91)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:108)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:503)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:320)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:186)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:146)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:350)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:446)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:409)
	at org.neuroml.model.util.NeuroMLConverter.<init>(NeuroMLConverter.java:73)
	at org.geppetto.model.neuroml.utils.OptimizedLEMSReader.readAllFormats(OptimizedLEMSReader.java:75)
	at org.geppetto.model.neuroml.utils.OptimizedLEMSReader.readAllFormats(OptimizedLEMSReader.java:67)
	at org.geppetto.model.neuroml.test.LEMSConversionServiceTest.createDomainModel(LEMSConversionServiceTest.java:219)
	at org.geppetto.model.neuroml.test.LEMSConversionServiceTest.testNeuron(LEMSConversionServiceTest.java:110)

**Comment by clausagerskov** [comment]
do you expect this build to only work with certain (old) versions of JRE and/or JDK?

**Comment by clausagerskov** [comment]
seems to not fail at that specific point with jdk8
